### ISSUE TITLE
Options to migrate the browser extension to new merged platform

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#11]
We have not talked about this in the TT SOW, but we should decide what we want to do about it.

**Comment by dasaderi** [comment]
Possibly related issues
- [Issue #163](https://github.com/PREreview/rapid-prereview/issues/163) on rapid-prereview repo
- [Issue #176](https://github.com/PREreview/rapid-prereview/issues/176) on rapid-prereview repo

**Comment by jheretic** [comment]
Rolling into #79
