### ISSUE TITLE
Licensed under CC-BY 4.0

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#112]
When you submit DOI, the review will be licensed under CC-BY 4.0 and PREreview will then add "CC-BY 4.0" under reviews.

**Comment by dasaderi** [comment]
Licence: https://creativecommons.org/licenses/by/4.0/

We can add the tag https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en and link to the link above.

**Comment by jheretic** [comment]
Duplicate of #1
