### ISSUE TITLE
Welcoming dialog box says "Welcome to Outbreak Science Rapid PREreview"

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#126]
![Dialog Box](https://user-images.githubusercontent.com/64230315/105220425-8b50de00-5b0c-11eb-8a1e-595d2f285dbd.png)

Can we update the wording to say,
"Welcome to PREreview.org
This platform was designed to facilitate rapid and long-form, open review of preprints.
Here you can:
1. Find rapid and long-form reviews of existing preprints.
2. Request reviews of preprints (your own, or preprints you are interested in).
3. Review preprints (as an individual, with a mentor, or in collaboration with co-reviewers).
Get Started"

Please use the same layout and formatting for now. This will most likely need to be updated again once the community pages are up in February.

**Comment by rudietuesdays** [comment]
Updated on the dev site!

http://prereview-dev.azurewebsites.net/

<img width="1669" alt="Screen Shot 2021-01-20 at 7 14 57 PM" src="https://user-images.githubusercontent.com/10843135/105256517-e3f79980-5b53-11eb-9698-69d3f651089b.png">


Please close if it looks good @murkatr

**Comment by murkatr** [comment]
@rudietuesdays Can we remove the "Get Extension" as that only works for the OSrPRE site at the moment?

**Comment by rudietuesdays** [comment]
Yup, updated on the dev site!
http://prereview-dev.azurewebsites.net/

**Comment by murkatr** [comment]
Awesome! Thank you @rudietuesdays!

**Comment by murkatr** [comment]
@rudietuesdays - Daniela and I updated the language for the fresh cookie dialog box (while we don't have the homepage up):

Welcome to the new PREreview.org, a site for the crowdsource of preprint reviews.

This is the marriage between two preprint review platforms, PREreview.org and outbreaksci.prereview.org. If you are a user of either of these platforms, your information has been migrated to this new site. If you are a new user, welcome to the family! 

Here you can:
1. Read rapid and long-form reviews of existing preprints.
2. Request reviews of preprints (your own, or preprints in which you are interested in seeing community feedback).
3. Review preprints (as an individual, with a mentor, or in collaboration with co-reviewers).
4. Find and join communities that are reviewing and discussing research relevant to you or start your own community. 

Get Started

**Comment by murkatr** [comment]
@rudietuesdays I'll move this to a new issue so that it's clear.
