### ISSUE TITLE
Longform Review on front page should be dashed --> "Long-form review"

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#129]
<img width="429" alt="Screen Shot 2021-01-20 at 2 13 05 PM" src="https://user-images.githubusercontent.com/13750121/105247504-bc8bd700-5b29-11eb-8181-eebffeefa109.png">

**Comment by murkatr** [comment]
Also here:
![Long-form example #2](https://user-images.githubusercontent.com/64230315/105248178-cfeb7200-5b2a-11eb-9b50-9117225ddeea.png)

**Comment by rudietuesdays** [comment]
Found all instances on the site (there were a couple others as well) and fixed them! Up on the dev site: http://prereview-dev.azurewebsites.net/

Please close if it looks good @dasaderi

**Comment by murkatr** [comment]
Looks like all instances on the dev site are updated. Thanks, @rudietuesdays!
