### ISSUE TITLE
Rapid review help missing for some questions 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#132]
- @dasaderi to add wording for help buttons for the questions missing it

**Comment by harumhelmy** [comment]
Labeling this issue as a quick fix, because it is as long as we have the text :)

**Comment by dasaderi** [comment]
See text below for each question

- **"Is sufficient detail provided to allow reproduction of the study?"** add help (**?**) text that says "Would another research group be able to reproduce these findings based solely on the information present in the manuscript, particularly the methods section and, if present, any supplementary/supporting information?"
- "Are the methods and statistics appropriate for the analysis?" add help (**?**) text that says "Do you think the methods used to analyze the data were adequately chosen and utilized to answer the research question(s)?"
