### ISSUE TITLE
Data link exists?

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#134]
I typed xyz in the data box and it did not complain. I think we talked about having a way to ensure that it's an active website? I believe @harumhelmy was saying something about this?

**Comment by rudietuesdays** [comment]
Pushed a fix to the dev site! http://prereview-dev.azurewebsites.net

**Comment by murkatr** [comment]
On the dev site, I see the "xyz" is accepted, and on the staging site, I see the same error as when tested with a link:
![error with link](https://user-images.githubusercontent.com/64230315/106794849-38981b80-660e-11eb-8a56-36f3f84ef881.png)
