### ISSUE TITLE
More space needed between preprint info and Read Reviews/Add Review(s)/Add Request bar

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#135]
The Read Reviews/Add Review(s)/Add Request bar overlaps a bit with the preprint information (with the light grey background). Can more space be created there?

![Space needed](https://user-images.githubusercontent.com/64230315/105248812-f067fc00-5b2b-11eb-8152-712c621b5cde.png)

**Comment by murkatr** [comment]
![Uploading Space needed.png…]()

**Comment by rudietuesdays** [comment]
Added on dev, please close if it looks good @murkatr 

For example: http://prereview-dev.azurewebsites.net/preprints/doi-10.1101-833392#reviews

**Comment by rudietuesdays** [comment]
Ah, thanks for clarifying! Didn't realize some titles could be so long. I pushed a fix to develop that allows for variable height based on the content of the header, so now there shouldn't be anymore funky overlap.

**Comment by murkatr** [comment]
Beautiful! Thank you for the fix, @rudietuesdays!
