### ISSUE TITLE
Conflict of Interest Error

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#136]
If the Conflict of Interest box is not checked after a rapid review is filled out then it doesn't get addressed if the user chooses to work on a long-form review.

![No COI dialog box](https://user-images.githubusercontent.com/64230315/105261244-26b17580-5b44-11eb-9f9e-3542bfa8e5e4.png)

**Comment by rudietuesdays** [comment]
Thanks for flagging. This is a known issue that will be fixed thru the submit reviews workflow update in #122 . Wanted to make sure you know I'm working on it via that one and not skipping it!
