### ISSUE TITLE
User Setting page updates

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#137]
![User Setting page](https://user-images.githubusercontent.com/64230315/105262073-d555b600-5b44-11eb-8202-1bfac4d88184.png)

- [x] Please center the text under "Welcome to PREreview!"
- [x] Change the bolded "public" --> "active" in both places (under "Personas" and in the dialog box that pops up when you click "Make active")
- [x] I didn't see an "Edit" button for the Anonymous persona

**Comment by harumhelmy** [comment]
Hi @murkatr ! PR #140 fixes the the first two. We thought folks shouldn't be able to edit their anonymous persona, that's why the edit button isn't there -- let us know if you'd like that functionality added in.

**Comment by murkatr** [comment]
Thank you @harumhelmy! I must have missed your comment – sorry. As stated today, your plan works well for the anonymous persona, so we won't worry about that editing functionality.
