### ISSUE TITLE
User Settings: Enable Notifications Error

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#138]
When toggling "Enable notifications", this request error pops up:

![When trying to enable notifications](https://user-images.githubusercontent.com/64230315/105267291-477aca80-5b46-11eb-81a7-aa7174d9138f.png)

**Comment by murkatr** [comment]
@harumhelmy I added "murpkatr@gmail.com" here and what showed up was "foo@bar.com". When I toggle either email to enable notifications, the same error message popped up.
![Notifcation evolution](https://user-images.githubusercontent.com/64230315/106786709-b4409b00-6603-11eb-909a-f3c5f849a2a9.png)

**Comment by jheretic** [comment]
This should now be fixed.
