### ISSUE TITLE
Thanks before even starting rapid review

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#154]
I noticed that the "Thank you for your contribution!" message is present even if I haven't started a review.
![No rapid](https://user-images.githubusercontent.com/64230315/106787971-37162580-6605-11eb-93c6-7409ab3058bc.png)
![Before starting rapid review](https://user-images.githubusercontent.com/64230315/106787980-3b424300-6605-11eb-9b07-d3f3835bcfb6.png)

**Comment by rudietuesdays** [comment]
Yes, this was part of the wireframes and includes an ask to review the code of conduct. Is this no longer desired, or should it be changed or moved?

**Comment by murkatr** [comment]
Agreed to remove only the first sentence, "Thank you for your contribution!"
