### ISSUE TITLE
Add option to leave feedback after CoC "cancel"

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#155]
After reading the Code of Conduct (CoC), the option to "CANCEL" can lead the user to the option of providing feedback on why they don't want to join the PREreview family. I don't believe we have a form to fill out at the moment; @dasaderi please correct me if I am wrong about this.

![Cancel  result](https://user-images.githubusercontent.com/64230315/106804632-8024a480-661a-11eb-9ac4-a890c0fa4183.png)

**Comment by murkatr** [comment]
@rudietuesdays will update the language around "trust"

**Comment by dasaderi** [comment]
New language for this pop up:

We are sorry you can't join our community at this moment. We hope you come back soon!

If you have any questions or concerns, please don't hesitate to contact us at [contact@prereview.org](contact@prereview.org). You can also give us anonymous feedback via this [feedback form](https://forms.gle/ASDSmhLLJexgDpPv5). 

Thank you!
