### ISSUE TITLE
Updates to adding an event in community pages

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#157]
Events need to also support:
- [x] time of event
- [x] range of dates
- [ ] dedicated field for a link to registration –e.g. evite, Zoom

Double-check that the added event is successfully submitted.

**Comment by murkatr** [comment]
@jheretic I tried adding an event today to the new Open Reviewers community (🥂 ) and I got the following error:
![Adding an event](https://user-images.githubusercontent.com/64230315/115484578-e4153d00-a207-11eb-895c-165490058761.png)
![Event error](https://user-images.githubusercontent.com/64230315/115484581-e5466a00-a207-11eb-924e-99d69e174a88.png)

**Comment by rudietuesdays** [comment]
I believe this is fixed via #330! Please close out if complete.
