### ISSUE TITLE
New link for the "Give Feedback" banner 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#161]
Feedback form: https://forms.gle/BjHvfBWXYVchUwvs9

**Comment by murkatr** [comment]
@dasaderi is this the same feedback form you want to use after reading the CoC and deciding to not sign up on PREreview?

**Comment by dasaderi** [comment]
@murkatr and @georgiamoon if you have a minute to review the[ new feedback form](https://forms.gle/BjHvfBWXYVchUwvs9), please do. But not a huge hurry.
