### ISSUE TITLE
help text for "rapid review" and "longform review"

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#191]
Please add a ? next to Rapid Review that says:

"A Rapid Review is a structured form with yes/no/n.a./not sure answer options designed for researchers with subject-of-matter expertise to provide a quick, but accurate feedback to a preprint. To provide more in-depth feedback, please use the Longform Review below."

"A Longform Review is a space designed for researchers with subject-of-matter expertise to provide longer, and more in-depth feedback to a preprint. It can be authored by one or more users. To add a co-reviewer, save your draft and click on + Add Co-Reviewer. To invite someone to edit your review before submitting, save your draft and click on + Add Mentor. When submitted, the Longform Review is assigned a digital object identifier (DOI) via Zenodo."

Maybe too long? @murkatr?

**Comment by harumhelmy** [comment]
@dasaderi Can you confirm where you'd like this help text? Here?

![Uploading Screen Shot 2021-02-23 at 13.47.33.png…]

**Comment by dasaderi** [comment]
@harumhelmy sorry for the late reply. I was thinking of adding it next the Rapid Review name here and same for Long-form
![Screen Shot 2021-03-02 at 2 26 12 PM](https://user-images.githubusercontent.com/13750121/109723694-4d12f980-7b63-11eb-87aa-299eaa6bcd7a.png)
