### ISSUE TITLE
Date on the imported reviews are of date of import

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#193]
I'm not sure if this is inevitable but reporting in case it's a bug
<img width="1359" alt="Screen Shot 2021-02-10 at 9 19 56 AM" src="https://user-images.githubusercontent.com/13750121/107546486-41926b00-6b81-11eb-98d7-1a725a9f4453.png">

**Comment by jheretic** [comment]
Closing this as I believe we discussed in the meeting that this isn't a priority and there's no easy way to rectify it due to the state of the old Prereview V1 database.
