### ISSUE TITLE
Request do not visualize in Read Reviews

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#194]
<img width="1356" alt="Screen Shot 2021-02-10 at 9 23 55 AM" src="https://user-images.githubusercontent.com/13750121/107546965-c8dfde80-6b81-11eb-8601-c7b6953f326d.png">

This preprint says in the homepage it has one request, but I don't see the request under read review.

**Comment by rudietuesdays** [comment]
This is expected behavior! Should we list the number of requests, if there are any, on this tab? And should users be able to see who made the request (this was not a feature on OSrPRE)?

**Comment by rudietuesdays** [comment]
Bumping the above question! @dasaderi any thoughts?

**Comment by dasaderi** [comment]
Sorry, seeing this now. I think maybe we weren't clear on this. I seemed to remember we had that users could see the number of requests and who made them, but perhaps that was PREreview V1. I would like to be able to see who requested and how many requests there are. So maybe add that to the Request tab? It can be just a list or a total number with the avatars of the requester. As the integration with the OPS preprint servers is done, we'll be able to show if one of them is the author and highlight that.

**Comment by dasaderi** [comment]
Can we close this one?

**Comment by rudietuesdays** [comment]
@dasaderi yes please close if it looks good to you! Related to #314
