### ISSUE TITLE
When we expand with the carrot on the main search page reviews don't render

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#197]
<img width="797" alt="Screen Shot 2021-02-10 at 9 30 26 AM" src="https://user-images.githubusercontent.com/13750121/107547848-c5008c00-6b82-11eb-9747-a61a734049d0.png">

This preprint has a long-form review. Is it supposed to show, at least in part, when user expands from the preprint on the main search page?

**Comment by rudietuesdays** [comment]
I believe this has been fixed -- at @dasaderi can you verify and close if so?

**Comment by dasaderi** [comment]
Yes, I can see the rapid review. When there is a long-form review though, it does not display. Can we add a link to the full view of the long-form review here?
<img width="1054" alt="Screen Shot 2021-04-02 at 10 21 33 AM" src="https://user-images.githubusercontent.com/13750121/113438334-38fa2c00-939d-11eb-9be7-a0245481a576.png">
