### ISSUE TITLE
Make hovering over name of longform review author clearly a clickable step to read the review

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#198]
<img width="569" alt="Screen Shot 2021-02-10 at 9 32 50 AM" src="https://user-images.githubusercontent.com/13750121/107548074-10b33580-6b83-11eb-80df-4a30393ee35a.png">

It is unclear that user can click on name to read the review. Maybe make it go italic or raise as a button when hovering over name?

**Comment by rudietuesdays** [comment]
Closing; obsolete after #321
