### ISSUE TITLE
Please remove the comments for this Rapid Review

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#206]
An Open Reviewer's mentee (Andrew Lopez) added their long-form review to their rapid review comments and they want the written comments removed so they can add and re-format a new long-form review once the OSrPRE data is imported. 

This is the related preprint:
https://prereview.org/preprints/doi-10.1101-2020.11.13.380030

**Comment by murkatr** [comment]
@jheretic This particular preprint was on both platforms and I see the OSrPRE rapid review hasn't been manually loaded yet. Do you think we can get this done soon?

**Comment by jheretic** [comment]
This rapid review was missed in the import for some reason, I've manually added it to the database now.
