### ISSUE TITLE
Way to show number of reviews and sort by that 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#209]
I realized that we don't have a way to show the number of total reviews. I know we don't like what OSrPRE had at the top left, but are we going to have an alternative? I found that handy.

**Comment by murkatr** [comment]
This has now been solved with this:
![number of preprints](https://user-images.githubusercontent.com/64230315/115486365-66ebc700-a20b-11eb-9a18-4ec68ce506b7.png)
