### ISSUE TITLE
Remove/fix links to permalinks and dowload data for rapid review because broken

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#217]
![Screen Shot 2021-02-23 at 2 00 16 PM](https://user-images.githubusercontent.com/13750121/108914014-a0bf9900-75df-11eb-96ca-0d02e8fd8b06.png)

**Comment by harumhelmy** [comment]
This is partly fixed for now! I need to investigate how to allow for downloading data of rapid reviews if that's still a desirable feature @dasaderi.

**Comment by dasaderi** [comment]
Thank you @harumhelmy. Yes, it would be very nice if we can easily download the data from each review instead of having to go through the API query.
