### ISSUE TITLE
Expose the reviewed preprint's uuid in the /rapidReviews endpoint

### ISSUE THREAD

**Issue by harumhelmy** [PREreview/prereview#225]
Per [this issue](https://github.com/PREreview/rapid-prereview/issues/116) in the former OSrPRE repo, bioRxiv would like the following information to be exposed in order to be able to display/link to PREreview content on their preprint pages: 

- preprint DOI, 
- review title, 
- date, 
- reviewer author name, 
- link back to PREreview

Our API exposes all the above yay 🎉 except that the /rapidReviews GET index endpoint doesn't expose the `uuid` of the reviewed preprint, which bioRxiv will need to link back to PREreview. It's be an easy fix, but I just want to make sure I'm not overlooking anything, @jheretic

**Comment by jheretic** [comment]
That sounds right. I'm working on some additional API fixes on the `api-permissions` branch, I'll just slot this change in there since I'm aiming that for today anyway, if that sounds good to you @harumhelmy

**Comment by murkatr** [comment]
@harumhelmy @jheretic I believe for preprints with multiple rapid and long-form reviews, we also wanted to provide the option of displaying the count of reviews instead of listing all the reviews individually. @dasaderi does this sound correct?
