### ISSUE TITLE
Fix proportions of text and image

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#232]
The proportions on the first section of the home page seem odd? The text is too big relative to the image of the people reaching for the paper.

**Comment by dasaderi** [comment]
This is also related to changing the general styles across the website according to [design systems on Figma](https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=1757%3A0)

**Comment by rudietuesdays** [comment]
@dasaderi updated on dev site! https://prereview-dev.azurewebsites.net/
