### ISSUE TITLE
Make clear cards can be flipped

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#233]
The cards are cool but they don't invite me to click them. That is they dont seem like buttons maybe we can add a drop shadow or something?

**Comment by rudietuesdays** [comment]
@dasaderi I added some more box shadow and increased the change on hover, let me know how that works! https://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
Thank you,u @rudietuesdays. I still think it's hard to know that by clicking on them you flip them. Can we do that when user hovers on them they flip rather than with a click?

**Comment by rudietuesdays** [comment]
@dasaderi Yes I can do that! But then confirming that the front of the cards will *not* have links on them, because it wouldn't be possible to click on those links if the card flips on hover. So there will be links on the back of the cards, but no longer on the front. Is this ok?

**Comment by dasaderi** [comment]
Good point. I think that is preferable. Thank you!

**Comment by rudietuesdays** [comment]
@dasaderi updated on the dev site! http://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
Great! Thank you!
