### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#235]
- [x] Code for Science and Society: https://codeforscience.org/
- [x] Code of Conduct: https://content.prereview.org/coc
- [x] Creative Common Attribution License: https://creativecommons.org/licenses/by/4.0/

**Comment by rudietuesdays** [comment]
I know there's a link to the code of conduct that needs to be added, but where on the page should the CSS and CC license links go?

**Comment by dasaderi** [comment]
Code for Science and Society is named in the Donate portion when we say they are our fiscal sponsor.
The license is in the footer.

**Comment by rudietuesdays** [comment]
@dasaderi updated on dev site! https://prereview-dev.azurewebsites.net/
