### ISSUE TITLE
Content for homepage

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#243]
@rudietuesdays Here is a consolidation of the content for the homepage based on your [merged PR](https://github.com/PREreview/prereview/pull/227) and [Figma](https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=1713%3A1082).

- **Header includes:** Preprint Review Platform, Programs (Open Reviewers, LivePREJCs), Resources (Resource Center, API, GitHub), Communities, Blog, About (Mission, Team, How we are funded, Code of Conduct, Privacy Policy), Donate, Log In / Sign Up
- **Links to resource cards:** ...
- [Screenshots](https://github.com/PREreview/prereview-project-assets/tree/master/screenshots)

**Comment by dasaderi** [comment]
I'm going to break down this in individual issues for clarity and close this issue.

**Comment by rudietuesdays** [comment]
That works for me!
