### ISSUE TITLE
Header menu + links

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#248]
See [figma](https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=1482%3A0) for layout.

Some of these pages don't yet exist on Ghost, but I'm working on that content.

Header, left to right, **level 1** and _level 2_:

- **Preprint Review Platform**--> _How it works_ (https://content.prereview.org/about-the-platform), _Go to platform_ (https://prereview.org/reviews) 

- **Programs** --> _Open Reviewers_ (https://content.prereview.org/openreviewers), _LivePREJC_ (https://content.prereview.org/liveprejcs) 

- **Resources** --> _Resource Center_ (https://content.prereview.org/resources, _API_ (https://prereview.org/API - not sure), _GitHub_ (https://github.com/PREreview/prereview) 

- **Communities**: https://prereview.org/communities)

- **Blog**: https://content.prereview.org

-  **About** --> _Mission_ (https://content.prereview.org/mission), _People_ (https://content.prereview.org/people), _How we are funded_ (https://content.prereview.org/funding), _Code of Conduct_ (https://content.prereview.org/coc), _Privacy Policy_ (https://content.prereview.org/)

- **Donate** (not sure about the link, but see issue #189) 

- **Log In / Sign Up** (https://prereview.org/login

**Comment by rudietuesdays** [comment]
@dasaderi updated on the dev site! http://prereview-dev.azurewebsites.net/
