### ISSUE TITLE
Links for buttons and text

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#250]
- BUTTON Join us and start reviewing now: https://prereview.org/login
- BUTTON Explore Communities: https://www.prereview.org/communities
- BUTTON Stay connected via our newsletter: https://mailchi.mp/97886570610a/prereview-newsletter-signup
- BUTTON Learn more and get involved: https://content.prereview.org/openreviewers) (not active yet
- LINK in TEXT Code of Conduct: https://content.prereview.org/coc
- LINK in TEXT Code for Science and Society: https://codeforscience.org/
- LINK in TEXT Creative Common Attribution 4.0 international license: https://creativecommons.org/licenses/by/4.0/

**Comment by rudietuesdays** [comment]
@dasaderi updated on dev site! https://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
Thank you. The only thing is making sure that the links change somehow when hovering over them for accessibility. Some do some don't (e.g., code for science and society).

Also, not sure if this is useful, but the banner should be as it is in the current stage and not with the link to the OASPA page. 

The preprint review platform link goes to a page that looks a bit broken

![Uploading Screen Shot 2021-03-22 at 10.00.55 AM.png…]()

**Comment by rudietuesdays** [comment]
@dasaderi Thanks for these notes! Updated on the dev site http://prereview-dev.azurewebsites.net/
