### ISSUE TITLE
Form for "Stay Connected" block in footer

### ISSUE THREAD

**Issue by rudietuesdays** [PREreview/prereview#251]
Is there a link / embed for this?

**Comment by dasaderi** [comment]
Link to Mailchimp newsletter sign up https://mailchi.mp/97886570610a/prereview-newsletter-signup.

**Comment by dasaderi** [comment]
@murkatr I just signed up using my gmail but receive no confirmation email. Can we set it up so that we get those confirmation emails where people have to actually confirm again to be added?

**Comment by rudietuesdays** [comment]
@dasaderi sign up link added on the dev site! http://prereview-dev.azurewebsites.net/
