### ISSUE TITLE
quotes for the carosel

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#254]
Inexperience is the greatest barrier to gaining experience. Not only do I not know where to start, I also do not know how to get there. Furthermore, the only advice I have ever received on the topic [of peer review] has been "Don't do it. It’s a waste of time that doesn't contribute to your career", which epitomizes the core problems causing the rot we see in peer review. - Juan Manuel Vazquez, PREreview Open Reviewer 2021

If we really want to diversify science we need to diversify the people who are labeled as "expert" in a field and [who] have the power to evaluate the quality of their peers' work. - Natalia Torres, PREreview Open Reviewer 2021

Science has a racism issue. Many discovered this issue recently with the murder of George Floyd and Breonna Taylor. But we (people of color and underrepresented in science) knew about this a while ago. I believe to balance the inequalities in the scientific enterprise, we should tackle different angles that include but are not limited to scientific training, recruitment, and support. Peer review is an important stage for scientific progress so by diversifying the reviewer pool we can push the needle forward and start to provide different voices to the reviewing process. - Joel Encarnacion-Rosado, PREreview Open Reviewer 2021

I gained confidence in my own abilities as an "expert" and a reviewer, which is what I hoped to get out of the programme. The discussions of inequity in science and peer review, both in our cohort and with invited editors went beyond what I expected from the programme and were super empowering. - Katarina Grobicki, PREreview Open Reviewer 2021

The importance of diversifying the pool of reviewers also means breaking down the Ivory Tower of science and the review process that happens "behind closed doors" to create a more open and equitable environment for reviewing and publishing scientifically rigorous papers. Radically changing the representation in the peer review process is an important part of creating an inclusive scientific community. - Gina Calco, PREreview Open Reviewer 2021

My expectations were fully met and beyond. I felt that the discussions on non-violent communication tied with the anti-bias/systems of oppression discussions really highlighted how valuable and important this program really is to our broader scientific community. I am happy to have also become part of this growing community. - Sergio Redondo, PREreview Open Reviewer 2021

I think diversifying STEM is the best chance we have to keep driving our fields forward. In order to produce good science, we need perspective from a variety of different people and taking the initiative to explicitly introduce that diversity by being conscious of training students from a variety of backgrounds is the best way of doing so. - Andrew Lopez, PREreview Open Reviewer 2021

I envision a diverse academic reviewership pool would be immune to such prevarication about the realities of our society, would not look at "diversity-focused research" as a box to check when determining the impact of a study, but would be able to make this a center focus of their respective fields. - Zaki Molvi, PREreview Open Reviewer 2021

In my opinion, diversifying the reviewer pool must take into account a number of components, including geography, race, disability, gender, class and career stage. In terms of geographical diversity, we need to extend the pool beyond academics in the northern hemisphere and academics at specific universities perceived as “elite” and “prestigious. - Katarina Grobicki, PREreview Open Reviewer 2021

More personally, diversifying the reviewer pool means including people who have similar lived experiences as me, who can see the frequently problematic issues with diversity in science - especially in genetics and other human studies - and the dire consequences of these problems. But, importantly, diversifying the reviewer pool means including scientists who are actually affected by these issues, who will fight to correct these issues by highlighting them in their reviews. - Juan Manuel Vazquez, PREreview Open Reviewer 2021

Please continue to train and recruit young reviewers. - Kishore Wary, PREreview Open Reviewer Mentor 2021

I found getting involved in the peer review process challenging. When I was a graduate student, journal editors seemed reluctant to include me as a peer reviewer. Most often, they did not want to challenge the status quo in peer reviewing. - PREreview Open Reviewer 2021

**Comment by rudietuesdays** [comment]
@dasaderi would it be possible to cut this list down, similar to the press strata? I can put all of these in but it's unlikely a user will see more than 4-5 of them.

**Comment by dasaderi** [comment]
Yes, I agree! @murkatr I'm selecting 6.

Inexperience is the greatest barrier to gaining experience. Not only do I not know where to start, I also do not know how to get there. Furthermore, the only advice I have ever received on the topic [of peer review] has been "Don't do it. It’s a waste of time that doesn't contribute to your career", which epitomizes the core problems causing the rot we see in peer review. - Juan Manuel Vazquez, PREreview Open Reviewer 2021

Please continue to train and recruit young reviewers. - Kishore Wary, PREreview Open Reviewer Mentor 2021

Science has a racism issue. Many discovered this issue recently with the murder of George Floyd and Breonna Taylor. But we (people of color and underrepresented in science) knew about this a while ago. I believe to balance the inequalities in the scientific enterprise, we should tackle different angles that include but are not limited to scientific training, recruitment, and support. Peer review is an important stage for scientific progress so by diversifying the reviewer pool we can push the needle forward and start to provide different voices to the reviewing process. - Joel Encarnacion-Rosado, PREreview Open Reviewer 2021

If we really want to diversify science we need to diversify the people who are labeled as "expert" in a field and [who] have the power to evaluate the quality of their peers' work. - Natalia Torres, PREreview Open Reviewer 2021

My expectations were fully met and beyond. I felt that the discussions on non-violent communication tied with the anti-bias/systems of oppression discussions really highlighted how valuable and important this program really is to our broader scientific community. I am happy to have also become part of this growing community. - Sergio Redondo, PREreview Open Reviewer 2021

I found getting involved in the peer review process challenging. When I was a graduate student, journal editors seemed reluctant to include me as a peer reviewer. Most often, they did not want to challenge the status quo in peer reviewing. - PREreview Open Reviewer 2021

**Comment by rudietuesdays** [comment]
@dasaderi added on the dev site! http://prereview-dev.azurewebsites.net/
