### ISSUE TITLE
press & awards

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#255]
Screenshots: https://github.com/PREreview/prereview-project-assets/tree/master/screenshots

@rudietuesdays Can we have that the links open new page when user clicks on screenshots in carousel?

- ASAPbio_award: https://asapbio.org/sprint-recap
- PLOS ECR Community guest post: https://ecrcommunity.plos.org/2018/10/18/guest-post-learning-about-preprints-with-prereview/
- Nature OSrPRE: https://www.nature.com/articles/d41586-020-00613-4
- No Manifesto podcast: https://www.nomanifestos.com/episodes/4
- The Lancet: https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(21)00011-5/fulltext
- Midas Network: https://midasnetwork.us/outbreak-science-prereview-a-platform-for-pre-prints-for-2019-ncov-studies/
- bio2040 podcast: https://bio2040.com/2018/04/09/opening-up-the-opaque-peer-review-process-with-sam-daniela-from-prereview/
- Research Professional news: https://www.researchprofessionalnews.com/rr-news-uk-open-access-2020-3-new-preprint-review-site-issues-call-for-papers-on-covid-19/
- eLife featured article: http://alice.mbi.ucla.edu/uploads/6/0/5/7/60576915/elife.38532__1_.pdf
- EPFL: https://actu.epfl.ch/news/pre-prints-and-journal-clubs-empowering-the-next-g/
- Nature Index: https://www.natureindex.com/news-blog/three-online-tools-aimed-at-improving-preprints
- Uni Pittsburgh: https://www.natureindex.com/news-blog/three-online-tools-aimed-at-improving-preprints
- South China Morning Post: https://www.natureindex.com/news-blog/three-online-tools-aimed-at-improving-preprints
- SPARC: https://sparcopen.org/news/2020/opencon-community-members-support-rapid-covid-response-through-preprints/
- JROST award: https://investinopen.org/blog/jrost-rapid-response-fund-awardees/

**Comment by dasaderi** [comment]
Trimmed down version:

- ASAPbio award: https://asapbio.org/sprint-recap

- JROST award: https://investinopen.org/blog/jrost-rapid-response-fund-awardees/

- Nature OSrPRE: https://www.nature.com/articles/d41586-020-00613-4

- The Lancet: https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(21)00011-5/fulltext

- Nature Index: https://www.natureindex.com/news-blog/three-online-tools-aimed-at-improving-preprints

- South China Morning Post: https://www.natureindex.com/news-blog/three-online-tools-aimed-at-improving-preprints

- SPARC: https://sparcopen.org/news/2020/opencon-community-members-support-rapid-covid-response-through-preprints/

- bio2040 podcast: https://bio2040.com/2018/04/09/opening-up-the-opaque-peer-review-process-with-sam-daniela-from-prereview/

- No Manifesto podcast: https://www.nomanifestos.com/episodes/4

**Comment by rudietuesdays** [comment]
@dasaderi thank you! Do you have brief descriptions for each of these? Without those they won't be screenreader-accessible

**Comment by dasaderi** [comment]
I can give you a title for each ones if needed. I'm just in a wall of call this afternoon, but will add as soon as I can.

**Comment by rudietuesdays** [comment]
Only if you want something specific! Otherwise I'll reference the article or award in each title

**Comment by rudietuesdays** [comment]
Just realized the link for the South China morning post is a duplicate of the Nature Index article! Do you have the correct link?

**Comment by rudietuesdays** [comment]
@dasaderi all added on the dev site, reflects the figma and not new updates as per our meeting today. just need the link for the South China article and it's ready to go! http://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
Sorry. Here it is https://www.scmp.com/news/china/article/3075431/will-coronavirus-kill-dinosaur-world-academic-publishing

**Comment by rudietuesdays** [comment]
@dasaderi thanks! updated http://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
@rudietuesdays, reopening this to add text to each link and have design match [Figma](https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=1482%3A0) as new design by @georgiamoon.


Below is info in the order that is currently on the website with **Title**/text/Read more link.

- **PREreview Awarded "_Best in Show_" at the ASAPbio #PreprintSprint 2020** / In the fall of 2020, PREreview was one of 20 projects who participated in the [ASAPbio Design Sprint: Encouraging Preprint Curation and Review](https://asapbio.org/sprint). Our team contributed with two submissions, one in which we proposed a model of engagement based on mentorship and collaborative review (proposal [here](https://asapbio.org/transforming-peer-review-through-mentorship-and-community-engagement)) and one in collaboration with the C19 Rapid Review Publishers Initiative (proposal [here](https://asapbio.org/covid-19-rapid-review-a-joint-publishers-initiative-to-engage-the-community-on-the-review-of-covid-19-preprints)). At the final pitch presentation on December 3, our team was awarded "Best in Show" with the first pitch. Read more https://asapbio.org/sprint-recap.

- **PREreview Awarded the JROST Rapid Response Fund** / In the fall of 2020, JROST announced the [Rapid Response Fund](https://investinopen.org/blog/jrost-rapid-response-fund/) _"to create a means to give back to the open infrastructure and technology community."_ PREreview was one of eight projects who were awarded. Read more https://investinopen.org/blog/jrost-rapid-response-fund-awardees/

- **Nature: Open peer-review platform for COVID-19 preprints** / Just a few weeks before the COVID-19 pandemic hit the world, we launched [Outbreak Science Rapid PREreview,](https://outbreaksci.prereview.org) a platform for the rapid community review of outbreak-related preprints–now a community on the new preview.org. In this short Nature commentary, Project Directors Drs. Daniela Saderi and Michael Johansson presented the platform to the community. Read more https://www.nature.com/articles/d41586-020-00613-4

- **The Lancet: Lessons from the influx of preprints during the early COVID-19 pandemic** / The COVID-19 pandemic led to an unprecedented increase in the uptake of preprints within the scientific community. Outbreak Science Rapid PREreview is mentioned in this commentary on The Lancet as the tool that allows researchers to conduct public reviews of COVID-19 preprints. Read more https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(21)00011-5/fulltext

- **Nature Index: Three online tools aimed at improving preprints** / PREreview showcased as one of three tools _"aimed at helping researchers produce better preprints."_ Read more https://www.natureindex.com/news-blog/three-online-tools-aimed-at-improving-preprints

- **South China Morning Post: Will the coronavirus kill off the ‘dinosaur’ world of academic publishing?** / PREreview Co-Founder and Director Dr. Daniela Saderi was interviewed by journalist Linda Lew for this piece on the future of publishing post-pandemic. Read more https://www.scmp.com/news/china/article/3075431/will-coronavirus-kill-dinosaur-world-academic-publishing 

- **SPARC Community Member Highlight** / PREreview Leadership Team member and OpenCon alum Dr. Monica Granados was interviewed by SPARC to present our work in the context of the pandemic to the community. Read more https://sparcopen.org/news/2020/opencon-community-members-support-rapid-covid-response-through-preprints/

- **bio2040 Podcast: Opening up the opaque Peer Review Process with Sam & Daniela from PREreview** Want to learn about PREreview's first baby steps and what motivated us to work on this project? Listen to PREreview Co-Founders Drs. Samantha Hindle and Daniela Saderi talk about it in this 2018 interview with Entrepreneur and Angel Investor Flavio Rump. Read more /https://bio2040.com/2018/04/09/opening-up-the-opaque-peer-review-process-with-sam-daniela-from-prereview/

- **No Manifesto Podcast: A chat with PREreview Co-Founder and Neuroscientist Daniela Saderi** Curious about the context PREreview started? Spoiler alert, it begins with a couple of somewhat frustrated but optimistic early-career (neuro)scientists. Read more https://www.nomanifestos.com/episodes/4

**Comment by rudietuesdays** [comment]
updated on the dev site https://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
Looks great, thank you @rudietuesdays. I will close this issue.
