### ISSUE TITLE
Small changes to homepage

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#257]
@rudietuesdays we got some feedback from @Monsauce and I'm summarizing here top to bottom of the homepage:

- [x] Make it so that header text does not wrap around as window gets smaller but goes to the condensed three lines menu style when too little space
- [x] Remove grey step from image at top (I know you suggested this, Rae, and we said it was fine before, sorry)
- [x] If possible make image at top a bit bigger
- [x] Change text at the top under tag line to match the one on [Figma](https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=1482%3A0)
- [x] Change red button text to only say "Start reviewing now" as the "join us" is in the text now
- [x] Under the search bar block, please realign content as shown on Figma, with the first block of text and screenshot centered, and ensuring the two buttons that say "Stay connected..." and "Learn more..." are aligned

Thank you!

**Comment by rudietuesdays** [comment]
Thanks @dasaderi ! I've knocked out the quicker ones, but is it possible to send an image that doesnt have the step included? If not I can edit it out, but if you've got one like that already then I can simply swap them out. Thanks!

**Comment by dasaderi** [comment]
I added [svg](https://github.com/PREreview/prereview-project-assets/blob/master/illustrations/PREreview-homepage-illustration-nostep.svg), [png](https://github.com/PREreview/prereview-project-assets/blob/master/illustrations/PREreview-homepage-illustration-nostep.png), and ai for the illustration without the step to the assets repo.

**Comment by dasaderi** [comment]
If possible to put the two yellow buttons on the same line, that would be great. :D Everything else looks GREAT! Thank you!

**Comment by murkatr** [comment]
@rudietuesdays I'll drop the embedded HTML for the footer newsletter here as well as Slack:


<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://prereview.us2.list-manage.com/subscribe/post?u=59f5a6fb4d4e4c2764dd6b2c8&amp;id=ea4641711a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Stay connected.</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_59f5a6fb4d4e4c2764dd6b2c8_ea4641711a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

**Comment by rudietuesdays** [comment]
@dasaderi thanks! these are all now integrated: http://prereview-dev.azurewebsites.net/

**Comment by dasaderi** [comment]
Beautiful! Thank you!
