### ISSUE TITLE
Update Ghost top menu bar and logo to match website

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#258]
@joehand let me know if you have trouble entering Ghost.

**Comment by rudietuesdays** [comment]
@dasaderi updated! https://content.prereview.org/

**Comment by dasaderi** [comment]
Thank you! Looks great! A couple of things:

- The logo seems to crush into the bar (see below)
- The link to the platform seems to go nowhere.
![Screen Shot 2021-03-24 at 9 35 50 AM](https://user-images.githubusercontent.com/13750121/112347804-6bf93d00-8c84-11eb-836e-497bd041abb5.png)

**Comment by rudietuesdays** [comment]
I'm not able to replicate either of these errors, so I'm flagging to discuss during our call!

**Comment by jheretic** [comment]
Fixed!
