### ISSUE TITLE
Create material-ui theme based on PREreview style guide

### ISSUE THREAD

**Issue by jheretic** [PREreview/prereview#26]
We want to eventually migrate from the home-grown React widgets inherited from Outbreak Science to a theme based on a more complete and standardized UI toolkit. Currently we're exploring creating a material-ui theme based on [the style guide](https://github.com/PREreview/prereview_style_guide) to see if that's a good match.

**Comment by rudietuesdays** [comment]
Closing as complete!

**Comment by murkatr** [comment]
@rudietuesdays Thank you for completing this! Can you please link us to the new style guide here?
