### ISSUE TITLE
M6: API Needs Summary

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#262]
@jheretic @rudietuesdays @harumhelmy **Here are the remaining needs to complete Milestone 6 ([amended agreement](https://docs.google.com/document/d/1afVROrS8ctO4ZB6-ZJN9gZ79xJY4duyKEJ5twksKU4k/edit)):**

- [x] PREreview to verify with Ted at bioRxiv/medRixv that they have what they need for integration on their end
- [ ] Once the new script is complete, PREreview can email Europe PMC with an update (@harumhelmy, I know you said emailing isn't necessary, but we would like to touch base with them anyway. Can you point us to the issue that includes the "cron job script to update the Europe PMC files automatically" as you mentioned in our 3 March 2021 Draft email to bioRxv email?)
- [ ] Work with eScire to complete OPS integration work, so the third-party sites working with Public Knowledge Project–e.g. RINarXiv and SciELO can have basic integration with PREreview.org - Daniela has just created a [repo](https://github.com/PREreview/api) for the API integration work so that we can keep track of work and coordinate better with eScire.
- [x] The [API page](https://www.prereview.org/api/docs) looks useful, but we are waiting on further documentation for users to read at the top as an introduction to what they are looking at and how to use the API and API keys.

Code clean-up for new styling are in progress:
- component work [here](https://github.com/PREreview/prereview/issues/40)
- frontend [here](https://github.com/PREreview/prereview/issues/259) and it's related PR [here](https://github.com/PREreview/prereview/pull/256)

It would be useful to work on a new timeline for this together so that we can share it with the funder.

**Comment by jheretic** [comment]
The summary API documentation is now complete and live on the site.

**Comment by murkatr** [comment]
The script for Europe PMC is completed. Waiting on the FTP info to wrap up that integration.

**Comment by murkatr** [comment]
@jheretic Any updates on the FTP info?
