### ISSUE TITLE
Change text on User Draft page

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#264]
![Screen Shot 2021-03-24 at 3 54 25 PM](https://user-images.githubusercontent.com/13750121/112394064-505c5980-8cb9-11eb-93aa-65e43f076133.png)

Please change to say

Collaboration
Invites
No invites yet.
Drafts
No review drafts saved.

**Comment by dasaderi** [comment]
@dasaderi to test this workflow.

**Comment by rudietuesdays** [comment]
@dasaderi updated on the dev site! https://prereview-dev.azurewebsites.net
