### ISSUE TITLE
Email notification toggle does not work properly

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#268]
When try to toggle individual email to enable notification, it only changes the first one no matter which one I click on
![Screen Shot 2021-03-24 at 4 03 15 PM](https://user-images.githubusercontent.com/13750121/112394829-9108a280-8cba-11eb-9f87-ff840838fb33.png)

**Comment by dasaderi** [comment]
I also only can delete the first email but not the others.

**Comment by dasaderi** [comment]
related to issue #269

**Comment by jheretic** [comment]
Fixed by #284
