### ISSUE TITLE
Design: Wireframe of a profile page

### ISSUE THREAD

**Issue by georgiamoon** [PREreview/prereview#27]
We need to adapt the profile page for users to include more metadata and features, e.g.

- [ ] Badges (see the mentorship program badges)
- [ ] Groups / Communities (E.g Outbreak Science, Mentorship Program, C19 Rapid Review) or other groups)
- [ ] Possible a place to see draft reviews that users have started and saved
- [ ] User defined expertise areas, e.g. "what am I offering mentorship or support on"
- [ ] User defined needs areas, e.g. "what am I looking for mentorship on"

**Comment by carijyao** [comment]
Created wireframe for the current profile page on Figma
