### ISSUE TITLE
COVID dashboard header messed up

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#272]
When going to the dashboard I see the double banner (which I understand is an issue that will go away with design systems application) but I also don't see the logo and instead I see half of a search bar.
![Screen Shot 2021-03-24 at 4 38 16 PM](https://user-images.githubusercontent.com/13750121/112397523-800e6000-8cbf-11eb-8f0f-d78e5b8c27e1.png)

**Comment by harumhelmy** [comment]
Fixed by #285 🎉
