### ISSUE TITLE
Reading reviews filters

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#280]
We need to add a way for users to only look at one rapid review at the time. We have wireframes for filters but have not implemented any yet.

At the very least I'd propose we add:

- way to display only one rapid review by clicking on the reviewer's avatar
- Way to filter rapid reviews by community 

Tagging @rudietuesdays @georgiamoon for discussion

**Comment by harumhelmy** [comment]
The staging site has been fixed for this. Could you review it, @dasaderi?

**Comment by dasaderi** [comment]
Looks great! Thank you, @harumhelmy!

**Comment by dasaderi** [comment]
I just realized that the filter by community per preprint has not been implemented. So I'm re-opening this issue.
