### ISSUE TITLE
Double scroll down gets stuck in platform page

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#294]
![Screen Shot 2021-03-31 at 12 19 27 PM](https://user-images.githubusercontent.com/13750121/113198978-6dde7580-921b-11eb-9071-d4152d733f73.png)

I'm not sure why it is, but when first landing no review platform I can't scroll down to the bottom unless I click somewhere on the page first. There appear to be two scrolling thingy on the side. Why is that?

**Comment by rudietuesdays** [comment]
@dasaderi is this issue persisting for you? I'm not able to replicate it. Thanks!

**Comment by dasaderi** [comment]
Nope. It's gone. I'll close it.
