### ISSUE TITLE
List of contributions on profile links to reviews twice 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#300]
If a user has done both the rapid and long-form review of a preprint, under their profile there will be links to the same page for both and there is no way to distunguish them. I wonder if we can make it so that the link to the long-form review goes to the actual long-form and not the rapid review.

<img width="944" alt="Screen Shot 2021-04-06 at 1 26 26 PM" src="https://user-images.githubusercontent.com/13750121/113774325-f8234f80-96db-11eb-9230-39c16922e0e6.png">

**Comment by harumhelmy** [comment]
In the new design, we distinguish a user's activity as below, FYI! 
![Screen Shot 2021-04-08 at 11 33 35](https://user-images.githubusercontent.com/13320420/114065521-bf64b100-9868-11eb-89e9-4833decb9166.png)

**Comment by dasaderi** [comment]
Okay, cool! Thank you, @harumhelmy!
