### ISSUE TITLE
Language to ask users to input email address

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#301]
The goal is to invite users, passed and new, to add their contant information making it clear why we need it that they can opt out of notifications and display of that information.

Some draft language that I'd love @georgiamoon and you all at TT feedback on is:

"We have not found a public email address on your ORCID account. Please add a valid email address to your PREreview profile so that we can reach out should we need to alert you of a change in our [Privacy Policy](https://content.prereview.org/privacypolicy) or any other major platform change. We will _not_ share your contact information without your authorization. In the profile settings, you can choose to opt out of website notifications as well as hide your contact information in your public persona's profile."

**Comment by harumhelmy** [comment]
I don't feel I have expertise to edit the rest of the language, but I would change the first sentence to "We were not able to import your email address from your ORCID record."

**Comment by dasaderi** [comment]
Yes that works better, thank you! <3

**Comment by georgiamoon** [comment]
@dasaderi will this be via email? Or on the website? What's the context / medium the how they will experience this?

Proposed Edit:

> We were not able to import your email address from your ORCID record. 
> 
> In order to receive key notifications, e.g. updates to our Privacy Policy, notification of activity on the platform, or other platform changes, please add a valid email address to your PREreview profile. 
> 
> We will not share your contact information. In the profile settings, you can opt out of website notifications as well as switch your account to be public or anonymized.

**Comment by dasaderi** [comment]
@georgiamoon it would be a warning message so a red box I presume, in the profile page for the user only to see with action to input email address in settings? @rudietuesdays may have a different idea. But whatever it is, it should be something that invites the user to add a contact information. @georgiamoon your suggested edits are great. I made some minor changes!

We were not able to import your email address from your ORCID record.

In order to receive key notifications, _e.g_., updates to our Privacy Policy, notification of activity on the platform in response to a review request, or other platform changes, please add a valid email address to your PREreview profile.

We will not share your contact information. In the profile settings, you can opt out of website notifications as well as switch your account to be public or anonymized.

**Comment by harumhelmy** [comment]
@dasaderi Here's what it could look like in the profile page:
![Screen Shot 2021-04-15 at 10 59 04](https://user-images.githubusercontent.com/13320420/114891138-a19fca80-9dd9-11eb-8406-a1a73858b574.png)

As you can see I made a small edit, as the persona switch dropdown is right below this information and I fear the original last sentence is redundant.

**Comment by dasaderi** [comment]
Perfect! Thank you @harumhelmy!
