### ISSUE TITLE
Change date format to spelling out Month and day

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#303]
<img width="517" alt="Screen Shot 2021-04-08 at 8 17 40 AM" src="https://user-images.githubusercontent.com/13750121/114052487-f0ca8600-9842-11eb-8559-26b28c53fc13.png">

@rudietuesdays I think we talked about this early on, but then forgot to bring this up again. We need dates to spell out month and day as it can be confusing. Alternatively we can use YYYY/MM/DD format.

**Comment by harumhelmy** [comment]
Hi @dasaderi, I made this fix per a now-closed issue #99 that @murkatr opened. It's on staging, but not on the production site yet. 
![Screen Shot 2021-04-08 at 11 33 35](https://user-images.githubusercontent.com/13320420/114054923-482a1f80-985e-11eb-905e-bfad69dc1fb7.png)
