### ISSUE TITLE
[STAGING] DOI and preprint title links

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#304]
@rudietuesdays going through the current staging site (so please apologies if that's something you are already fixing and it has not made it here yet) and finding that the doi of the preprints are not links that go to the preprint server, e.g.:

<img width="560" alt="Screen Shot 2021-04-08 at 11 28 41 AM" src="https://user-images.githubusercontent.com/13750121/114078566-f8e3ef00-985d-11eb-9a78-5ad981982111.png">

Also, clicking on the title of the preprint which looks like a link, doesn't go anywhere. We would need both the title of the preprint and the doi to be links to the preprint on the preprint server, ideally opening as a new window. Thanks!

**Comment by rudietuesdays** [comment]
@dasaderi updated on the dev site! https://prereview-dev.azurewebsites.net
