### ISSUE TITLE
When hovering over the number that we decided to remove on Outbreak Science community page goes to blank

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#305]
I'm not sure if this will go away with the new design, but I noticed that the Outbreak Science community page still has that weird number inherited from OSrPRE next to the numbers of reviews and requests, and when you mouse over it, it goes to some white page loop from which you don't come back unless your re-load the page. 

<img width="398" alt="Screen Shot 2021-04-08 at 1 58 04 PM" src="https://user-images.githubusercontent.com/13750121/114095753-a7922a80-9872-11eb-82b9-5fa140d30415.png">

<img width="637" alt="Screen Shot 2021-04-08 at 1 57 59 PM" src="https://user-images.githubusercontent.com/13750121/114095659-8a5d5c00-9872-11eb-9003-0f0d8dd2559a.png">

**Comment by jheretic** [comment]
As anticipated, this is now fixed in the new design.
