### ISSUE TITLE
Toggle for enabling notifications in profile gives error

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#310]
<img width="1120" alt="Screen Shot 2021-04-12 at 9 23 46 PM" src="https://user-images.githubusercontent.com/13750121/114496732-7056ad00-9bd5-11eb-818a-f5c66f4c6079.png">

**Comment by murkatr** [comment]
I also get this error, but slightly differently when I toggle the "Turn on/off notifications":
![Notification Toggle Error](https://user-images.githubusercontent.com/64230315/114591265-919fb380-9c3e-11eb-8c2a-52058867c576.png)

**Comment by jheretic** [comment]
This is now fixed.
