### ISSUE TITLE
Adding new email addrress in profile - error occurred

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#311]
<img width="1112" alt="Screen Shot 2021-04-12 at 9 25 41 PM" src="https://user-images.githubusercontent.com/13750121/114496867-b449b200-9bd5-11eb-907a-e3f9e883689e.png">

**Comment by jheretic** [comment]
The email login to sendgrid got blanked out in the azure settings somehow in the last deployment. I reset it and this is now working.
