### ISSUE TITLE
Design system inconsistency in colors

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#312]
I noticed that sometimes the banner is the main red for PREreview, sometime it is the light red. Maybe the design systems have not been deployed yet, so ignore this if that's the case
<img width="1438" alt="Screen Shot 2021-04-13 at 8 37 48 AM" src="https://user-images.githubusercontent.com/13750121/114580380-a88cd880-9c33-11eb-9491-a188efbad88b.png">

**Comment by murkatr** [comment]
Header text also has some inconsistencies.

**Comment by jheretic** [comment]
Fixed in #319
