### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by harumhelmy** [PREreview/prereview#32]
Tracking issue for adding unit tests to backend controllers (and maybe more? we'll see after coverage numbers):

- [ ] auth
- [ ] comment
- [ ] community
- [ ] docs
- [ ] fullReviewDraft
- [ ] fullReview
- [ ] group
- [ ] persona
- [ ] preprint
- [ ] rapidReview
- [ ] request
- [ ] searches
- [ ] tag
- [ ] user

**Comment by jheretic** [comment]
Closing in favor of more specific issues.
