### ISSUE TITLE
Visualizing longform reviews

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#321]
@rudietuesdays we had some users who could not find their longform reviews, but it was because they did not find it intuitive to expand the name to read the long form review. I wonder if one of two possible quick solutions could be implemented:

A) Make it obvious when hovering on name that it is clickable
B) Eliminate step of clicking on name to get to the partial view and then have the read more to expand as we now do.

I'd favor B.

<img width="529" alt="Screen Shot 2021-04-15 at 1 58 40 PM" src="https://user-images.githubusercontent.com/13750121/114937875-3c58d300-9df3-11eb-8e49-05b21f2e8e62.png">

**Comment by rudietuesdays** [comment]
Related to #198

**Comment by rudietuesdays** [comment]
Sounds good, going with option B and closing #198!

**Comment by dasaderi** [comment]
Ooops. Of course I did not remember that there was already a similar issue about this. :D Thanks for handling it so quickly.
