### ISSUE TITLE
Collapse Users in Moderator Settings

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#324]
@jheretic Can we have the users collapse under the community page settings for the moderators/admins? With so many members under OSrPRE, it takes a while to get down to the Events, Tags, and Templates on the same page. Thanks in advance!

**Comment by rudietuesdays** [comment]
Removed the quick fix label because I had thought this was in the sidebar box on the community pages, not the settings page. Planning to take a look on Monday!

**Comment by rudietuesdays** [comment]
@dasaderi just pushed a fix to staging for you to take a look at!

**Comment by murkatr** [comment]
@rudietuesdays Maybe Daniela will have better luck, but on staging in Chrome/Firefox/Safari, the Community Settings page spins and then times out for me, so I wasn't able to see the new collapse feature.
![No collapse feature](https://user-images.githubusercontent.com/64230315/117043645-5aaf4180-acc2-11eb-90cc-11e444aafc51.png)
![Community Settings users](https://user-images.githubusercontent.com/64230315/117042982-7ebe5300-acc1-11eb-8d85-859883de6844.png)

**Comment by dasaderi** [comment]
Same thing for me on staging.

<img width="869" alt="Screen Shot 2021-05-04 at 12 25 37 PM" src="https://user-images.githubusercontent.com/13750121/117058769-dd8cc800-acd3-11eb-8284-d178233a7ed4.png">

**Comment by harumhelmy** [comment]
Ah sorry it's so frustrating! This is also related to the server timing out.

**Comment by murkatr** [comment]
😍  ![members](https://user-images.githubusercontent.com/64230315/119199782-88c1af00-ba40-11eb-9d88-414e9c9782a2.png)
