### ISSUE TITLE
Community hashtag option

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#329]
@jheretic Can we have the option of a hashtag along with a Twitter handle for communities? For instance, our Open Reviewers is marked as a #OpenReviewers in our @PREreview_, but we wouldn't want to necessarily have just our handle listed.

**Comment by jheretic** [comment]
Not as a separate field, but support's been added for entering a hashtag instead of a Twitter handle, with linking and formatting happening appropriately.
