### ISSUE TITLE
Automate script that generates links for external partners, such as Europe PMC

### ISSUE THREAD

**Issue by harumhelmy** [PREreview/prereview#33]
Right now the script that generates links to reviews on PREreview sites lives in [this repo](https://github.com/PREreview/prereview-feed). When merged platform is launched, we want to:

- [ ] Update script accordingly
- [ ] Automate the job (Daniela is thinking every 24hrs)

Outstanding question:
- [ ] It shouldn't be difficult to automate the script, but I haven't looked into how we'd automate uploading it to Europe PMC's FTP server. @rudietuesdays @jheretic, ideas?

**Comment by murkatr** [comment]
@jheretic @harumhelmy Found where the GitHub issue was for automating the FTP script for Europe PMC. Please let me know when the script is ready, so I can email update Europe PMC. Thanks!

**Comment by rudietuesdays** [comment]
@jheretic @harumhelmy can we close this out?
