### ISSUE TITLE
Adding moderators and community members

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#330]
@jheretic I know we talked about a fix already in the works for the moderators, so thank you! I am definitely having trouble adding members as well.

**Comment by murkatr** [comment]
Along with adding moderators, is there an easier way to find a moderator that then drop-down with no order in the Admin Settings > Communities? Seems like the trick is to keep typing the first letter of the name until you find the person you are looking for.

**Comment by murkatr** [comment]
@jheretic Here’s my [video journey](https://www.loom.com/share/40c6eb355a6b487b9c51f9cc0221a94c?sharedAppSource=personal_library) trying to add an event, moderators, and members to the Open Reviewers community page.

**Comment by murkatr** [comment]
I took a similar journey with Firefox and Safari. 
- One difference I noticed with Firefox, in the Admin settings, the names are not highlighted as you click the first letter of the first name so it was a little more difficult to find Sam's name.

I also went back through to try adding my name as the moderator and member – and nothing happens as far as I can tell including seeing email invites come through.

**Comment by harumhelmy** [comment]
@murkatr Thank you so much for this super thorough video!! I'm sorry it's been frustrating to manage the communities. Just wanted to keep you posted that I'm working on this today and will let you know when you can test it on staging today!

**Comment by harumhelmy** [comment]
@murkatr It took me a bit to track down the issue, but I think I found it. It's not quite fixed yet and I have to log off for today, but I'll aim to get it fixed tomorrow.

**Comment by rudietuesdays** [comment]
@murkatr FYI we pushed a fix to dev for the "add events" bug! Still on top of moderators/users bug.

**Comment by murkatr** [comment]
@rudietuesdays I'm not seeing communities to add the events to and I don't have Admin Settings access to create a community to test this on. Maybe @dasaderi can try?

**Comment by murkatr** [comment]
Also, I made an example of a Community on our live site but now cannot delete it. I'm hoping this will be an option when the next updates are complete.

**Comment by dasaderi** [comment]
@rudietuesdays @murkatr I also don't have admin credentials on the dev site because I'm using your orcid sandbox account to test. :D

**Comment by murkatr** [comment]
To clean up this issue: we CAN now add moderators and community members. 

The deleting a community issue added to this thread is now a new issue [here](https://github.com/PREreview/prereview/issues/372).
