### ISSUE TITLE
When user chooses to not make email publicly available change display text

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#331]
Instead of saying "None provided" can we do one of two things?
a) not show that field at all
b) say "None publicly disclosed"

<img width="289" alt="Screen Shot 2021-04-21 at 12 49 51 PM" src="https://user-images.githubusercontent.com/13750121/115612589-4b7ecb80-a2a0-11eb-9b03-d20ddaae78c2.png">

**Comment by harumhelmy** [comment]
Fixed -- field is now hidden if the user doesn't have a public email.
