### ISSUE TITLE
Final name change for reviews

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#332]
Rapid PREreview / rapid PREreview
Full PREreview / full PREreview

**Comment by dasaderi** [comment]
After voting on this we reached a conclusion. @rudietuesdays please don't hate us. I'm marking this as LOW priority. If you get to it great, if not, we will deal with it. Thanks so much!

We would like the names on the front end only of the reviews to be changed to **Rapid PREreview** and **Full PREreview** which should reflect the back end, shorten the name and get rid of the hyphenation issue.  Obvious places where that should be changed:

- [ ] Read Reviews including help text
- [ ] Add Reviews in the point-to-point menu, the name and the help text
- [ ] Homepage card "Rapid and Full PREreviews"
- [ ] Search text: "315 preprints with 136 Full PREreviews, 122 Rapid PREeviews, and 262 requests"
- [ ] Search list e.g. Preprint 2 Rapid PREreviews | 2 Full PREreviews | 4 Requests
- [ ] Profile list of PREreview contributions.

Thank you!

**Comment by rudietuesdays** [comment]
I believe I caught these everywhere @dasaderi ! Up on the dev site, please close if complete! https://prereview-dev.azurewebsites.net

**Comment by dasaderi** [comment]
Thank you, @rudietuesdays. I'm seeing "rapid reviews" and "full reviews" and they should be "Rapid PREreviews" and "Full PREreviews". Sorry.

**Comment by rudietuesdays** [comment]
Whoops, sorry about that! Just pushed a fix, should be on the dev site in a few minutes @dasaderi

**Comment by dasaderi** [comment]
No problem at all. THANK YOU for following up on the name saga! :D

**Comment by rudietuesdays** [comment]
Happy to! Changes should be up by now, feel free to take a look @dasaderi :)

**Comment by dasaderi** [comment]
Looks great! Thank youuuuu!
