### ISSUE TITLE
Add the OSrPRE filters to the COVID-19 dashboard

### ISSUE THREAD

**Issue by harumhelmy** [PREreview/prereview#342]
- [ ] Recommended for peer review
- [ ] Recommended to others
- [ ] Has available code
- [ ] Has available data

**Comment by dasaderi** [comment]
Hi @rudietuesdays  and @jheretic. I wonder if there is a fix for this just not deployed yet. I don't recall exactly per our previous conversations. Thanks.

**Comment by jheretic** [comment]
@dasaderi Yep! There's an in-progress fix that just hasn't been deployed, we're working on testing it.
