### ISSUE TITLE
Full PREreview - undefined co-reviewer appears after saving draft

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#350]
I'm not sure this is a bug or it's expected behavior, but while testing the adding co-reviewer workflow I saved a draft full PREreview and saw that an avatar appeared at the top of the editor and when I hovered on it it said "undefined co-reviewer". This happened before I added a co-reviewer and mentor.
<img width="559" alt="Screen Shot 2021-05-03 at 1 51 36 PM" src="https://user-images.githubusercontent.com/13750121/116932452-216dc780-ac17-11eb-9238-e9f09f2168c7.png">

**Comment by rudietuesdays** [comment]
@dasaderi just pushed a fix to dev for this!
