### ISSUE TITLE
Event creation pop up gets stuck after user clicks Submit

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#354]
Possibly a very quick fix but marked as high priority because I think it can confuse people.

@rudietuesdays I tested the event creator tool on community pages on staging and found that after I click Submit the window does not disappear making me think it did not go through, but the event showed up in the background. I hit Sumbmit again and it created another one but still the window would not disappear.
<img width="804" alt="Screen Shot 2021-05-04 at 12 29 38 PM" src="https://user-images.githubusercontent.com/13750121/117059216-6a378600-acd4-11eb-97c1-80dff1461715.png">

**Comment by harumhelmy** [comment]
Hi @dasaderi! I looked into this and it seems to only happen on the staging site, which makes me think it's related to the optimization work that @jheretic is making progress on! Just fyi.
