### ISSUE TITLE
Was this Full PREreview submitted empty? 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#360]
I see that this preprint has a full PREreview, but it looks like it's not there. @jheretic any idea what happened there?

https://prereview.org/preprints/38e996f7-297c-4b66-b92b-19e04f5aa94a/full-reviews/23f5e8d3-fecc-4a1d-8920-e6662ea4bd31

<img width="1395" alt="Screen Shot 2021-05-06 at 12 11 43 PM" src="https://user-images.githubusercontent.com/13750121/117352837-4d31bd00-ae64-11eb-9ace-7ed68935a84d.png">

**Comment by jheretic** [comment]
Hmm, I just looked in the database and it wasn't submitted empty, but it did somehow get disconnected from the preprint. At least according to the API, the mapping from `Preprint => Review` is there but the reverse relation of `Review => Preprint` is empty. The database model we're using should make that impossible. I'll do some more looking into it to see what could have happened, and I can also restore that connection in the database.

**Comment by dasaderi** [comment]
Here's another example
https://prereview.org/preprints/doi-10.1101-2021.02.20.21251855
