### ISSUE TITLE
If I click "see all members" in community page goes to Not Found

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#363]
<img width="997" alt="Screen Shot 2021-05-06 at 1 16 52 PM" src="https://user-images.githubusercontent.com/13750121/117360213-5a9f7500-ae6d-11eb-8a75-bf447d10d28e.png">

<img width="1436" alt="Screen Shot 2021-05-06 at 1 16 04 PM" src="https://user-images.githubusercontent.com/13750121/117360132-45c2e180-ae6d-11eb-9109-0a9994a832b1.png">

**Comment by murkatr** [comment]
![See all members times out](https://user-images.githubusercontent.com/64230315/119199936-d0483b00-ba40-11eb-96d7-b8f2fd5d7bb6.png)

**Comment by dasaderi** [comment]
I just tested this and it worked. Closing this issue.
