### ISSUE TITLE
Update Parcel to a stable release

### ISSUE THREAD

**Issue by thewilkybarkid** [PREreview/prereview#399]
Parcel has had its first release candidate released; this includes changes such as changing the JavaScript compiler ([actually in beta 3](https://v2.parceljs.org/blog/beta3/)).

After an initial test, the project as-in doesn't build.

**Comment by thewilkybarkid** [comment]
Usage of the ORM currently has a _lot_ of circular dependencies (where two entities depend on each other). The JS changes in Parcel seem to fail when building: `Cannot access 'Community' before initialization`

**Comment by thewilkybarkid** [comment]
https://github.com/parcel-bundler/parcel/pull/6694 might help.

**Comment by thewilkybarkid** [comment]
Parcel 2.0.0 has now been released, but the app still doesn't build.

**Comment by thewilkybarkid** [comment]
I've managed to reproduce the Parcel problem and open a PR: https://github.com/parcel-bundler/parcel/pull/7293.

**Comment by thewilkybarkid** [comment]
In order to move this forward, we should remove the decorators and use [`EntitySchema`](https://mikro-orm.io/docs/entity-schema/) instead.

https://github.com/PREreview/prereview/issues/398#issuecomment-915031796 needs to be addressed though, as there is some code reliant on the use of decorators.

**Comment by thewilkybarkid** [comment]
I'm currently struggling to get `EntitySchema` to work with Parcel's scope hoisting as classes are renamed, whereas the ORM relies on them being unchanged (so they're different at runtime). This wasn't a problem with the decorators as they were processed by TSC before Parcel would try to change them(?). Options are probably either to disable Parcel's scope hoisting/optimisation or define them explicitly.

**Comment by thewilkybarkid** [comment]
> define them explicitly

This didn't work, the types seemingly allow for both a `class` and a `name` to be set, but the latter is ignored and the name of the class itself continues to be used.

I also looked at using types rather than classes, which works but you have to declare types everywhere (since you're just referring to them by a string).

Feels like the most pragmatic approach now is to just stop Parcel from mangling the names.

**Comment by KillerCodeMonkey** [comment]
hey gordon shumway :D. (nice avatar)

i saw your issues at parcel to use parcel v2.

I am using typeorm with sqlite in an electron app.
everything worked with parcel v2 beta3.1 but not with the final version.

I got it working by:

- deactivating scopeHoisting and optimizations.
- to avoid circular deps in entities - import you entities as with "type" and use relations as strings, e.g.

```TS
import type { person } from '../entities/person'

@Entity({ name: 'family' })
export class Family {
  @PrimaryGeneratedColumn()
  id: number

  // One family holds multiple patients
  @OneToMany('Person', 'family', { eager: true })
  patients: Person[]

  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date
}
```

PS: in the beta i needed to set a specific entity name, because parcels scopeHosting transformed the name of the class.
