### ISSUE TITLE
*idea*: add a field for users to attach files (e.g., jpg, png) to the review

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#4]
Now, I don't know if this is nuts, but an editor we have recruited for being a mentor for the mentoring program said that he runs a graduate level course on peer review in which his students are asked to review a preprint. One of the assignments is to do a graphical abstract of the preprint. I was thinking that would be a great thing to add if one had it for the review. One concern would be if someone uploaded some porn images or something like that. How would we check for that?

**Comment by rudietuesdays** [comment]
So the current rich text editor actually *does* allow for images and videos! We can remove this functionality, but it is already built in. As far as moderating, I think it would have to be assumed that no one will post something outside of community guidelines, and if they do, it will be moderated and removed, and they may be removed as well.

Let me know if you have further questions about this, or if this is sufficient please close out the issue. Thanks!

**Comment by rudietuesdays** [comment]
@dasaderi bumping this in case you have questions or it's ready to close!
