### ISSUE TITLE
rapid PREreview round up numbers 

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#409]
When multiple reviewers fill out a rapid PRE, the % shown on the aggregated viz should be round-up to the closest integer to avoid long decimal numbers such as in this case 

<img width="546" alt="Screen Shot 2021-09-27 at 8 59 34 AM" src="https://user-images.githubusercontent.com/13750121/134943928-96a28ac5-9668-40d1-bddc-2d9fa8b68cb0.png">

**Comment by thewilkybarkid** [comment]
> round-up to the closest integer

I'm taking this to be "round to the closest integer", that is 33.333 becomes 33, while 66.666 becomes 67.

**Comment by dasaderi** [comment]
Yes, I think that makes more sense. What do you think @thewilkybarkid?

**Comment by thewilkybarkid** [comment]
![image](https://user-images.githubusercontent.com/1784740/142855256-93ddc979-4280-4fb4-84ca-d0001e77c7a6.png)

Much better. 😃

**Comment by dasaderi** [comment]
Absolutely! Thanks Chris! <3
