### ISSUE TITLE
community moderator can't save edits to template or delete them

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#410]
Error occurs when community moderator tries to save an edited template or delete them. Interestingly I can do it successfully as an admin. 

@thewilkybarkid any chance you can please

- [x] Check why community moderators can't do the above action correctly
- [x] Check that templates that are saved correctly show up as available templates to load in full PREreview by community members

**Comment by thewilkybarkid** [comment]
I've been able to recreate this as a community moderator and not as an admin too: the former gets a `403 Forbidden` response when editing or deleting a template, but can create them successfully.
