### ISSUE TITLE
Add PREreview button not showing in community page

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#429]
A PREreviewer community moderator contacted us saying that the Add PREreview | Add request button does not show in their community page. See screenshot. 

@thewilkybarkid any idea why this is happening. I can see it in my browser and with my account.

<img width="400" alt="Chrome Screen Shot 2021-12-06 at 11 50 52 PM" src="https://user-images.githubusercontent.com/13750121/145290037-ecd94e13-362a-40dc-a2cf-ae4c25b66ba1.png">

**Comment by thewilkybarkid** [comment]
I've managed to recreate this problem in a test.

Looking at the logic, the settings button appears as it checks if you're an admin or one of your personas is an owner of the community:

https://github.com/PREreview/prereview/blob/2a5e9810bebe9217971fcec1adbde6a58029e29c/src/frontend/components/Community.js#L260-L263

But the add request/review button doesn't appear as it checks if you're an admin or if your _default_ persona is an owner, but it doesn't actually load the list of communities for your default persona (i.e. it's always empty):

https://github.com/PREreview/prereview/blob/2a5e9810bebe9217971fcec1adbde6a58029e29c/src/frontend/components/Community.js#L840-L847

**Comment by thewilkybarkid** [comment]
> checks if you're an admin or if your _default_ persona is an owner

Just realised it's checking it your default persona is a _member_ rather than an owner of a community.
