### ISSUE TITLE
Provide feedback to a user who tries to add a review or request a second time

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#44]
@georgiamoon and I noticed that when a reviewer tries to add a review to a preprint to which they have already written a review for, nothing happens and the system looks unresponsive. It would be good to have a pop up message that says that they can't review/request a review again for that preprint

**Comment by rudietuesdays** [comment]
We've updated this so the tabs get disabled after a user submits a review -- would this fix the issue?

For instance, if a user successfully submits a rapid review, they are redirected to the read reviews tab and the rapid reviews tab is disabled. Same workflow for a longform review (tho this will be updated a bit after the new wireframes are integrated)

**Comment by rudietuesdays** [comment]
Closing for now, happy to reopen or open a new issue if this needs a different solution!
